### ISSUE TITLE
SMTP Error

### ISSUE THREAD

**Issue by Eggysgames** [SirVoRaK/chess#5]
Hey there your package looks great but I'm running into errors trying to get the docker up and even running once. An SMTP Error that comes up and also access denied. I'm a bit confused because it seems related to login but I figured you could be a guest?

![image](https://github.com/SirVoRaK/chess/assets/113896751/198eb89b-241b-495f-bf01-ab56a89cd96f)

my .yml file is like this after setting up a basic mysql database in docker -

version: '3'

services:
  chess:
    image: chess
    environment:
      PORT: 3000
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
      MYSQL_DB: mydatabase
      DEBUG: false
      EMAIL_USER: user@outlook.com
      EMAIL_PASS: password

**Comment by rodolfoinfantini** [comment]
Hi!
It seems like you have a MySql and Email issue.
About MySql, it seems that you used the 3309 port for it instead of the default 3306, the node js app will try to connect to the 3306 port.
About email, you need to enter a valid outlook email and password, so it can use it to send the verification code to the users that register in the chess app.

**Comment by Eggysgames** [comment]
Hey thanks that did fix it! 

I did run into the issue now of black not being able to see whites first move, which I see was discussed in a closed issue, and he said he fixed it with something in the sockets.io but did not say how to fix that hmm. I am also running NodeJS v18

localhost is able to make rooms and player can join it all correctly only problem is the moves are not sent.

**Comment by rodolfoinfantini** [comment]
Yeah he didn't say how he fixed it but my guess is that it is because of the node version, it must be 16!
The dockerfile actually uses the node 16, so by running the instructions on the readme you should be able to run it properly.

Another question: does the over the board game mode works?

**Comment by rodolfoinfantini** [comment]
I've just reproduced the bug in windows, I'll work on a fix.

**Comment by rodolfoinfantini** [comment]
Just commited the fix, check if it works!
Just reclone the repo and follow the new instructions on the readme.
It now creates the mysql db inside the docker compose file. No need for an external mysql server.

**Comment by Eggysgames** [comment]
Hey mate it works perfect now! that's awesome! May I ask what you changed? :)

I still am using Node v18.5 but I do see in your code now it says from Node 16 so maybe it overwrites it to make it work? Or is that because I'm running it localhost.

**Comment by rodolfoinfantini** [comment]
Sure! It was a symbolic link to stockfish that works on linux but not on windows.
Because I just tried it on linux I just forgot about it, so I removed the symlink and used the actual path instead.

Yeah, the docker image uses the node 16 and not what is installed on your system.
If you take a look at the dockerfile you can see that it uses it.
It works only on 16 because of stockfish, for some reason it just won't run on newer versions.

**Comment by Eggysgames** [comment]
Ahh I see, glad you helped with that because I don't think I woulda found that haha! Thanks again, if you had a Github Sponsor sign up I woulda made a small donation as thanks 💯 

I will have a go at putting it on a vercel/server now to learn that part next like you did before I start custom changes 👍

**Comment by rodolfoinfantini** [comment]
I don't have it, but I appreciate a lot!
If you have any more questions, don't hesitate to open another issue, I'll be happy to help!
